-- MySQL Script generated by MySQL Workbench
-- Mon Dec 17 20:57:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cultiva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cultiva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cultiva` DEFAULT CHARACTER SET utf8 ;
USE `cultiva` ;

-- -----------------------------------------------------
-- Table `cultiva`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cultiva`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(80) NOT NULL,
  `emailUsuario` VARCHAR(80) NOT NULL,
  `senhaUsuario` VARCHAR(80) NOT NULL,
  `cpfUsuario` VARCHAR(45) NOT NULL,
  `telefoneUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `cpfUsuario_UNIQUE` (`cpfUsuario` ASC),
  UNIQUE INDEX `emailUsuario_UNIQUE` (`emailUsuario` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
